### ISSUE TITLE
Initialization failed on P5.48xlarge (EKS): "Unexpected group size 0"

### ISSUE THREAD

**Issue by Steboss** [aws/aws-ofi-nccl#1063]
## Description 
I am running a multi-node training job on AWS EKS using 2 p5.48xlarge instances. Despite having `hostNetwork`: true, privileged mode enabled, and EFA devices mounted, the `aws-ofi-nccl` plugin fails to initialize the RDMA protocol.

The specific error observed in the logs is:
```
NCCL WARN NET/OFI Unexpected group size 0
```
which forces NCCL to fall back to the Socket (TCP) transport layer, bypassing EFA entirely.

## Hardware
- Hardware: AWS p5.48xlarge (H100)
- Orchestrator: AWS EKS
- AMI: Amazon Linux 2023 (AL 2023-x64_64-nvidia-1.33)
- Base Container Image: `nvcr.io/nvidia/cuda-dl-base:25.06-cuda12.9-devel-ubuntu24.04` - (Ubuntu 24.04)
- NCCL Version: 2.27.3
- AWS OFI NCCL Version: 1.14.0 (Installed in `/opt/amazon/aws-ofi-nccl`)
- Libfabric Version: 1.22
- CUDA Driver: 535+ (compatible with CUDA 12.9 per logs)

## Input K8s manifest

I can provide you a manifest for reproducing the issue too, if needed. The work is related to this paradigm [jax-vllm-offloading](https://github.com/NVIDIA/JAX-Toolbox/tree/main/jax-inference-offloading) we're working on:

```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-vllm-multinode
  namespace: default
spec:
  network:
    enableDNSHostnames: true
    publishNotReadyAddresses: true

  replicatedJobs:
  # Gateway Pod
  - name: gateway
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: gateway
          spec:
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
            containers:
            - name: gateway-container
              image: MY_CONTAINER
              command:
              - bash
              - -c
              - |
                set -euo pipefail

                echo "=== Starting Gateway ==="
                echo "Gateway will listen on 0.0.0.0:50051"

                cd /opt/jtbx/jax-inference-offloading
                python -u jax_inference_offloading/controller/gateway.py 2>&1 | tee gateway.log

              env:
              - name: GATEWAY_PORT
                value: "50051"

              ports:
              - containerPort: 50051
                name: gateway
                protocol: TCP

              resources:
                requests:
                  cpu: "4"
                  memory: "8Gi"
                limits:
                  cpu: "8"
                  memory: "16Gi"

              volumeMounts:
              - name: shmem
                mountPath: /dev/shm

            volumes:
            - name: shmem
              emptyDir:
                medium: Memory
                sizeLimit: 8Gi

  # vLLM Node (Node 0)
  - name: vllm-node
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: vllm
          spec:
            serviceAccountName: jax-worker
            hostNetwork: true 
            dnsPolicy: ClusterFirstWithHostNet

            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: node-role
                      operator: In
                      values:
                      - jax
                  topologyKey: kubernetes.io/hostname

            containers:
            - name: vllm-container
              image: MY_CONTAINER
              env:
              - name: MY_HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              command:
              - bash
              - -c
              - |
                set -euo pipefail

                GATEWAY_HOST="${JOBSET_NAME}-gateway-0-0.${JOBSET_NAME}"
                export GATEWAY_URL="${GATEWAY_HOST}:50051"
                
                HOST_IP=$(hostname -I | awk '{print $1}')
                export RAY_HEAD_IP=${HOST_IP}
                export JAX_COORDINATOR_ADDRESS="${JAX_COORDINATOR_HOST}:${JAX_COORDINATOR_PORT}"
                echo "JAX Coordinator Address: ${JAX_COORDINATOR_ADDRESS}"

                echo "=== Starting on vLLM Node (Node ${JOB_COMPLETION_INDEX}) ==="
                echo "Gateway URL: ${GATEWAY_URL}"
                echo "Ray Head IP: ${RAY_HEAD_IP}"

                # 1. Wait for gateway to be ready
                echo "Waiting for gateway at ${GATEWAY_HOST}:50051..."
                python3 -c "
                import socket, time, sys
                host = '${GATEWAY_HOST}'
                port = 50051
                timeout = 120
                start = time.time()

                while True:
                    try:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(5)
                        if sock.connect_ex((host, port)) == 0:
                            sock.close()
                            print(f'Gateway ready at {host}:{port}')
                            sys.exit(0)
                    except Exception as e:
                        pass

                    if time.time() - start > timeout:
                        print(f'Timeout waiting for gateway')
                        sys.exit(1)
                    time.sleep(2)
                " || exit 1

                PIDS=()
                echo "Test gateway connection"
                echo "Test gateway connection"
                python3 -c "
                import os
                import sys
                import grpc

                url = os.environ.get('GATEWAY_URL')
                print(f'Gateway URL from env: {url}')

                if not url:
                    print('ERROR: GATEWAY_URL not set in environment')
                    sys.exit(1)

                try:
                    print(f'Connecting to {url}...')
                    channel = grpc.insecure_channel(url)
                    grpc.channel_ready_future(channel).result(timeout=10)
                    print(f'Successfully connected to gateway at {url}')
                except Exception as e:
                    print(f'Failed to connect to gateway: {e}')
                    sys.exit(1)
                "
                # Start Ray Head


                # 2. Start Ray Head
                echo "Starting Ray Head..."
                ray start \
                  --head \
                  --node-ip-address=${HOST_IP} \
                  --port=${RAY_PORT} \
                  --ray-client-server-port=${RAY_CLIENT_SERVER_PORT} \
                  --num-cpus=48 \
                  --num-gpus=8 \
                  --block \
                  --disable-usage-stats 2>&1 | tee ray-head.log &
                PIDS+=($!)

                sleep 10  # Let Ray start

                # 3. Start vLLM Rollout Controller (no GPU, connects to Ray)
                echo "Starting vLLM Rollout..."
                cd /opt/jtbx/jax-inference-offloading/examples
                export RAY_ADDRESS="${HOST_IP}:${RAY_PORT}"
                CUDA_VISIBLE_DEVICES="" ray status
                python -u rollout.py 2>&1 | tee rollout.log &
                PIDS+=($!)

                # Wait for all processes
                echo "All vLLM components started, waiting..."
                wait "${PIDS[@]}"
                echo "vLLM node completed"
              env:
              - name: JOB_COMPLETION_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']

              # General config
              - name: HF_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: huggingface-token
                    key: token
              - name: MODEL_NAME
                value: "meta-llama/Llama-3.1-8B-Instruct"
                
              #NCCL
              - name: NCCL_DEBUG
                value: "INFO" 
              - name: NCCL_PROTO
                value: "simple"
              - name: NCCL_NET_PLUGIN
                value: "/opt/amazon/aws-ofi-nccl/lib/libnccl-net-aws-ofi.so"

              - name: FI_PROVIDER
                value: "efa"
              - name: FI_EFA_USE_DEVICE_RDMA
                value: "1"
              - name: LD_LIBRARY_PATH
                value: "/usr/lib/x64_64-linux-gnu:/usr/local/cuda-12.9/compat/lib.real:/opt/amazon/efa/lib:/opt/amazon/ofi-nccl/lib:$LD_LIBRARY_PATH"

              - name: TORCH_CUDA_ARCH_LIST
                value: "9.0"
              # Gateway
              - name: GATEWAY_PORT
                value: "50051"
              - name: GATEWAY_URL
                value: "jax-vllm-multinode-gateway-0-0.jax-vllm-multinode:50051"

              # Ray settings
              - name: RAY_PORT
                value: "20527"
              - name: RAY_CLIENT_SERVER_PORT
                value: "24430"

              # CUDA settings
              - name: CUDA_DEVICE_ORDER
                value: "PCI_BUS_ID"
              - name: CUDA_DEVICE_MAX_CONNECTIONS
                value: "16"
              - name: CUDA_VISIBLE_DEVICES
                value: "0,1,2,3,4,5,6,7"

              # vLLM settings
              - name: VLLM_ENFORCE_EAGER
                value: "1"
              - name: VLLM_LOAD_FORMAT
                value: "dummy"
              - name: VLLM_GPU_MEMORY_UTILIZATION
                value: "0.7"
              - name: VLLM_TENSOR_PARALLEL_SIZE
                value: "8"  
              - name: VLLM_DISTRIBUTED_BACKEND
                value: "ray"  
              - name: VLLM_ATTENTION_BACKEND
                value: "TRITON_ATTN_VLLM_V1" 

              - name: NCCL_CUMEM_ENABLE
                value: "0"
              - name: NCCL_BUFFSIZE
                value: "16777216"

              # Trainer settings (passed through)
              - name: TRANSFER_MODE
                value: "grouped"
              - name: USE_POLYMORPHIC_MESH
                value: "0"
              # JAX
              - name: JAX_COORDINATOR_HOST
                value: "jax-vllm-multinode-jax-node-0-0" 
              - name: JAX_COORDINATOR_PORT
                value: "12345"
            
              # Debug
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "2"
              - name: VLLM_CONFIGURE_LOGGING
                value: "1"

              ports:
              - containerPort: 50051
                name: gateway
                protocol: TCP
              - containerPort: 20527
                name: ray
                protocol: TCP
              - containerPort: 24430
                name: ray-client
                protocol: TCP

              resources:
                limits:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"
                  hugepages-2Mi: "5120Mi"
                  memory: "32000Mi"
                requests:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"
                  hugepages-2Mi: "5120Mi"
                  memory: "32000Mi"

              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
                  - SYS_PTRACE
                  - NET_ADMIN
                privileged: true

              volumeMounts:
              - name: shmem
                mountPath: /dev/shm

            nodeSelector:
              node.kubernetes.io/instance-type: p5.48xlarge

            tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule

            volumes:
            - name: shmem
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi

  # JAX Node (Node 1)
  - name: jax-node
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: jax
          spec:
            serviceAccountName: jax-worker
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet

            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: node-role
                      operator: In
                      values:
                      - vllm
                  topologyKey: kubernetes.io/hostname

            containers:
            - name: jax-container
              image: MY_CONTAINER
              command:
              - bash
              - -c
              - |
                set -euo pipefail
                # 1. Define Variables FIRST
                GATEWAY_HOST="${JOBSET_NAME}-gateway-0-0.${JOBSET_NAME}"
                export GATEWAY_URL="${GATEWAY_HOST}:50051"

                # Use downward API or hostname -i for safer IP resolution
                HOST_IP=$(hostname -I | awk '{print $1}')
                export JAX_COORDINATOR_ADDRESS="${HOST_IP}:12345"
                export JAX_COORDINATOR_PORT="12345"

                echo "=== Starting on JAX Node (Node ${JOB_COMPLETION_INDEX}) ==="
                echo "Host IP: ${HOST_IP}"
                echo "Gateway URL: ${GATEWAY_URL}"
                echo "JAX Coordinator: ${JAX_COORDINATOR_ADDRESS}"
                echo "JAX Process Index: ${JAX_PROCESS_INDEX}"
                echo "JAX Process Count: ${JAX_NUM_PROCESSES}"

                # Wait for gateway
                echo "Waiting for gateway at ${GATEWAY_HOST}:50051..."
                python3 -c "
                import socket, time, sys
                host = '${GATEWAY_HOST}'
                port = 50051
                timeout = 180
                start = time.time()

                print(f'Checking connectivity to {host}:{port}...')

                while True:
                    try:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(5)
                        result = sock.connect_ex((host, port))
                        sock.close()

                        if result == 0:
                            print(f'Successfully connected to {host}:{port}')
                            sys.exit(0)
                    except Exception as e:
                        pass

                    elapsed = time.time() - start
                    if elapsed > timeout:
                        print(f'Timeout after {timeout}s waiting for {host}:{port}')
                        sys.exit(1)

                    if int(elapsed) % 10 == 0:
                        print(f'Port not ready yet (elapsed: {elapsed:.1f}s), retrying...')
                    time.sleep(2)
                " || exit 1

                echo "Gateway is ready!"
                # Start JAX trainer
                cd /opt/jtbx/jax-inference-offloading/examples
                echo "Starting JAX Trainer..."
                python -u trainer.py 2>&1 | tee trainer-node${JOB_COMPLETION_INDEX}.log

                echo "JAX trainer completed"

              env:
              # JobSet metadata
              - name: JOB_COMPLETION_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']

              # General config
              - name: HF_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: huggingface-token
                    key: token
              - name: MODEL_NAME
                value: "meta-llama/Llama-3.1-8B-Instruct"

              # JAX distributed config
              - name: JAX_COORDINATOR_PORT
                value: "12345"
              - name: JAX_NUM_PROCESSES
                value: "1"  # Single JAX node for now
              - name: JAX_PROCESS_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              - name: JAX_LOCAL_DEVICE_IDS
                value: "0,1,2,3,4,5,6,7"

              # CUDA settings
              - name: CUDA_DEVICE_ORDER
                value: "PCI_BUS_ID"
              - name: CUDA_DEVICE_MAX_CONNECTIONS
                value: "16"
              - name: CUDA_VISIBLE_DEVICES
                value: "0,1,2,3,4,5,6,7"

              - name: NCCL_CUMEM_ENABLE
                value: "0"
              - name: NCCL_BUFFSIZE
                value: "16777216"
              - name: TORCH_CUDA_ARCH_LIST
                value: "9.0"

              # XLA flags
              - name: XLA_FLAGS
                value: >-
                  --xla_gpu_enable_latency_hiding_scheduler=true
                  --xla_gpu_enable_command_buffer=FUSION,CUBLAS,CUDNN,CUSTOM_CALL
                  --xla_gpu_collective_permute_combine_threshold_bytes=8589934592
                  --xla_gpu_reduce_scatter_combine_threshold_bytes=8589934592
                  --xla_gpu_all_gather_combine_threshold_bytes=8589934592
                  --xla_gpu_all_reduce_combine_threshold_bytes=8589934592

              # Trainer settings
              - name: TRANSFER_MODE
                value: "grouped"
              - name: USE_POLYMORPHIC_MESH
                value: "0"

              # Debug
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "2"
              # NCCL
              - name: NCCL_DEBUG
                value: "INFO" 
              - name: NCCL_PROTO
                value: "simple"
              - name: NCCL_NET_PLUGIN
                value: "/opt/amazon/aws-ofi-nccl/lib/libnccl-net-aws-ofi.so"
            

              - name: FI_PROVIDER
                value: "efa"  # Force EFA provider
              - name: FI_EFA_USE_DEVICE_RDMA
                value: "1"
              - name: LD_LIBRARY_PATH
                value: "/usr/lib/x64_64-linux-gnu:/usr/local/cuda-12.9/compat/lib.real:/opt/amazon/efa/lib:/opt/amazon/ofi-nccl/lib:$LD_LIBRARY_PATH"
             

              # GATEWAY
              - name: GATEWAY_URL
                value: "jax-vllm-multinode-gateway-0-0.jax-vllm-multinode:50051"

              ports:
              - containerPort: 12345
                name: jax-coord
                protocol: TCP


              resources:
                limits:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"
                  hugepages-2Mi: "5120Mi" 
                  memory: "32000Mi"
                  cpu: "48"
                requests:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"
                  hugepages-2Mi: "5120Mi" 
                  memory: "32000Mi"
                  cpu: "48"

              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
                  - SYS_PTRACE
                  - NET_ADMIN
                privileged: true

              volumeMounts:
              - name: dshm
                mountPath: /dev/shm

            nodeSelector:
              node.kubernetes.io/instance-type: p5.48xlarge

            tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule

            volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 32Gi

  successPolicy:
    operator: All

  startupPolicy:
    startupPolicyOrder: InOrder

```

## Logs

The logs indicate that the plugin successfully loads and detects the EFA provider and the 32 NICs present on the P5 node. However, it immediately fails during the RDMA init phase:
```
[..]
[0] NCCL INFO NET/Plugin: Plugin name set by env to libnccl-net-aws-ofi.so
[0] NCCL INFO Successfully loaded external plugin aws-ofi
[0] NCCL INFO NET/OFI Initializing aws-ofi-nccl 1.14.0
[0] NCCL INFO NET/OFI Using Libfabric version 1.22
[..]
[0] NCCL INFO NET/OFI Using transport protocol RDMA (platform set)
[0] NCCL INFO NET/OFI Selected provider is efa, fabric is efa (found 32 nics)

[0] nccl_net_ofi_rdma_init:8063 NCCL WARN NET/OFI Unexpected group size 0
[0] nccl_net_ofi_create_plugin:218 NCCL WARN NET/OFI Failed to initialize rdma protocol
[0] nccl_net_ofi_create_plugin:335 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
[0] nccl_net_ofi_init:155 NCCL WARN NET/OFI Initializing plugin failed

[0] NCCL INFO plugin/net/net_v9.cc:57 -> 3
[0] NCCL INFO NET/Socket : Using [0]enp71s0:10.0.29.169<0>
```

## Additional Context
- Topology Detection: We suspect this might be an issue with how the plugin detects topology inside the container (Ubuntu 24.04) running on an AL2023 Host.
- Environment Variables: We have tried explicitly setting `NCCL_SOCKET_IFNAME` to the primary ethernet interface to ensure out-of-band communication uses the correct path, but the EFA failure happens before socket initialization.
- Isolation: The job runs, but performance is degraded as it falls back to TCP Sockets.
- Is there a specific requirement for `hwloc` or topology files that might be missing in the Ubuntu 24.04 base image that `aws-ofi-nccl` relies on to group the NICs correctly on P5 instances?

**Comment by anshumang** [comment]
@Steboss Thanks for sharing the log. Could you confirm if the EFA plugin is installed? Instructions here : https://github.com/aws/eks-charts/blob/master/stable/aws-efa-k8s-device-plugin/README.md

Our EKS friends have reviewed the manifest you shared and it looks good.

The `Selected provider is efa, fabric is efa (found 32 nics)` in the log is simply reporting what is present on the instance. The association with the job container happens when the request comes through the manifest which is handled by the EFA plugin where the EFA devices are mounted in the pod namespace. Only then the job can use it.

**Comment by anshumang** [comment]
@Steboss Thanks for helping to check this off the suspect list. Next, `hwloc` (that you have also mentioned in your initial report) which is used by the plugin and which in turn, will either use `libpciaccess` or `hwloc/topology-linux.c`. Running `lstopo` should also exercise `hwloc`. So, if you could share the output of that and it turns out that does not work either / does not display the expected EFA topology, then likely this is some EKS related setting (besides the manifest) being off.

**Comment by Steboss** [comment]
Another thing to consider, we're using `cupy` for running `nccl`
For example - little snippet: 
```python 

import cupy as cp
from cupy.cuda import nccl



def exchange_unique_id(hostname, is_master, port=DEFAULT_PORT):
    """
    Exchange NCCL unique ID between two processes.
    rank 0 (sender)  -> acts as server, generates and sends unique_id
    rank 1 (receiver)-> connects to server and receives unique_id
    Returns:
        comm_id (tuple): object suitable for NcclCommunicator
    """
    if is_master:
        # Generate NCCL unique ID once on master
        unique_id = nccl.get_unique_id()
        payload = pickle.dumps(unique_id, protocol=pickle.HIGHEST_PROTOCOL)
        header = struct.pack("!I", len(payload))

        # Minimal TCP server
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:
            server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            server.bind(("0.0.0.0", port))
            server.listen(1)
            print(f"[rank 0] Listening for NCCL unique ID connection on 0.0.0.0:{port}", flush=True)
            conn, addr = server.accept()
            with conn:
                print(f"[rank 0] Connection from {addr}, sending NCCL unique ID", flush=True)
                conn.sendall(header)
                conn.sendall(payload)
        print("[rank 0] Unique ID sent, continuing.", flush=True)
        return unique_id
    else:
        # Receiver: connect (with retries) and get unique ID
        while True:
            try:
                print(f"[rank 1] Connecting to {hostname}:{port} for NCCL unique ID", flush=True)
                with socket.create_connection((hostname, port), timeout=10) as sock:
                    header = recv_all(sock, 4)
                    (length,) = struct.unpack("!I", header)
                    payload = recv_all(sock, length)
                unique_id = pickle.loads(payload)
                print("[rank 1] Received NCCL unique ID.", flush=True)
                return unique_id
            except OSError as e:
                print(f"[rank 1] Connection failed ({e}), retrying in 1s...", flush=True)
                time.sleep(1)


# Select GPU (index is relative to CUDA_VISIBLE_DEVICES)
cp.cuda.Device(gpu_id).use()

# Exchange NCCL unique ID via tiny TCP server
comm_id = exchange_unique_id(hostname, is_master, port=DEFAULT_PORT)

# Create NCCL communicator for 2 ranks
comm = nccl.NcclCommunicator(2, comm_id, rank)
```

**Comment by Steboss** [comment]
@anshumang Thanks for the suggestion. We tried without `hostNetwork`, but the error still persists. I finally have a public manifest that you can use for testing. You just need an `HF_TOKEN` for accessing the model. 
Here is the manifest 
```yaml 
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-vllm-multinode
  namespace: default
spec:
  network:
    enableDNSHostnames: true
    publishNotReadyAddresses: true

  replicatedJobs:
  # Gateway Pod (separate, no hostNetwork)
  - name: gateway
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: gateway
          spec:
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
            containers:
            - name: gateway-container
              image: ghcr.io/nvidia/jax:jax-inference-offloading-2025-12-10
              command:
              - bash
              - -c
              - |
                set -euo pipefail

                echo "=== Starting Gateway ==="
                echo "Gateway will listen on 0.0.0.0:${GATEWAY_PORT}"

                cd /opt/jtbx/jax-inference-offloading
                python -u jax_inference_offloading/controller/gateway.py 2>&1 | tee gateway.log

              env:
              - name: GATEWAY_PORT
                value: "50051"

              ports:
              - containerPort: 50051
                name: gateway
                protocol: TCP

              resources:
                requests:
                  cpu: "2"
                  memory: "8Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"

              volumeMounts:
              - name: shmem
                mountPath: /dev/shm

            volumes:
            - name: shmem
              hostPath:
                path: /dev/shm
                type: Directory

  # vLLM Node (Node 0)
  - name: vllm-node
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: vllm
          spec:
            serviceAccountName: jax-worker
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet

            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: node-role
                      operator: In
                      values:
                      - jax
                  topologyKey: kubernetes.io/hostname

            containers:
            - name: vllm-container
              image: ghcr.io/nvidia/jax:jax-inference-offloading-2025-12-10
              command:
              - bash
              - -c
              - |
                set -euo pipefail
                apt-get update -y
                apt-get install -y hwloc 
                lstopo
                GATEWAY_HOST="${JOBSET_NAME}-gateway-0-0.${JOBSET_NAME}"
                export GATEWAY_URL="${GATEWAY_HOST}:${GATEWAY_PORT}"
                HOST_IP=$(hostname -i)
                export RAY_HEAD_IP=${HOST_IP}

                # Check for Gateway readiness
                echo "Waiting for gateway at ${GATEWAY_HOST}:${GATEWAY_PORT}..."
                python3 -c "
                import socket, time, sys
                host = '${GATEWAY_HOST}'
                port = int('${GATEWAY_PORT}')
                print(f'Checking connectivity to {host}:{port}...')
                timeout = 120
                start = time.time()

                while True:
                    try:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(5)
                        if sock.connect_ex((host, port)) == 0:
                            sock.close()
                            print(f'Gateway ready at {host}:{port}')
                            sys.exit(0)
                    except Exception as e:
                        pass

                    if time.time() - start > timeout:
                        print(f'Timeout waiting for gateway')
                        sys.exit(1)
                    time.sleep(2)
                " || exit 1

                PIDS=()
                echo "Test gateway connection"
                # Connect to gateway
                python3 -c "
                import os
                import sys
                import grpc

                url = os.environ.get('GATEWAY_URL')
                print(f'Gateway URL from env: {url}')

                if not url:
                    print('ERROR: GATEWAY_URL not set in environment')
                    sys.exit(1)
                try:
                    print(f'Connecting to {url}...')
                    channel = grpc.insecure_channel(url)
                    grpc.channel_ready_future(channel).result(timeout=10)
                    print(f'Successfully connected to gateway at {url}')
                except Exception as e:
                    print(f'Failed to connect to gateway: {e}')
                    sys.exit(1)
                "
                # Start Ray Head
                echo "Starting Ray Head..."
                ray start \
                  --head \
                  --node-ip-address=${HOST_IP} \
                  --port=${RAY_PORT} \
                  --ray-client-server-port=${RAY_CLIENT_SERVER_PORT} \
                  --num-cpus=48 \
                  --num-gpus=8 \
                  --block \
                  --disable-usage-stats 2>&1 | tee ray-head.log &
                RAY_PID=$!

                sleep 10  # Give time to Ray to settle

                # Start vLLM Rollout Controller
                echo "Starting vLLM Rollout..."
                cd /opt/jtbx/jax-inference-offloading/examples
                export RAY_ADDRESS="${HOST_IP}:${RAY_PORT}"
                CUDA_VISIBLE_DEVICES="" ray status
                python -u rollout.py 2>&1 | tee rollout.log &
                ROLLOUT_PID=$!

                wait ${ROLLOUT_PID}
                ROLLOUT_EXIT=$?
                echo "Rollout.py finished with code ${ROLLOUT_EXIT}"
                ray stop --force || true
                kill ${RAY_PID} 2>/dev/null || true
                echo "VLLM completed"
                exit ${ROLLOUT_EXIT}
              env:
              - name: NCCL_DEBUG
                value: "INFO"
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']

              # General config
              - name: HF_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: huggingface-token
                    key: token
              - name: MODEL_NAME
                value: "meta-llama/Llama-3.1-8B-Instruct"
              - name: MODEL_PATH
                value: "" # possibility to have a path for model
              # EFA
              - name: FI_PROVIDER
                value: "efa"
              # General VLLM
              - name: TORCH_CUDA_ARCH_LIST
                value: "9.0"
              # Gateway
              - name: GATEWAY_PORT
                value: "50051"
              - name: GATEWAY_URL
                value: "jax-vllm-multinode-gateway-0-0.jax-vllm-multinode:50051"
              # Ray settings
              - name: RAY_PORT
                value: "20527"
              - name: RAY_CLIENT_SERVER_PORT
                value: "24430"
              # CUDA settings
              - name: CUDA_DEVICE_ORDER
                value: "PCI_BUS_ID"
              - name: CUDA_DEVICE_MAX_CONNECTIONS
                value: "16"
              - name: CUDA_VISIBLE_DEVICES
                value: "0,1,2,3,4,5,6,7"
              # vLLM settings
              - name: VLLM_ENFORCE_EAGER
                value: "1"
              - name: VLLM_LOAD_FORMAT
                value: "dummy"
              - name: VLLM_GPU_MEMORY_UTILIZATION
                value: "0.4"
              - name: VLLM_TENSOR_PARALLEL_SIZE
                value: "8"
              - name: VLLM_DISTRIBUTED_BACKEND
                value: "ray"
              # NCCL
              - name: NCCL_BUFFSIZE
                value: "16777216"
              # - name: NCCL_SOCKET_IFNAME
              #   value: "enp71s0"
              - name: VLLM_WORKER_MULTIPROC_METHOD
                value: "spawn"
              - name: RAY_BACKEND_LOG_LEVEL
                value: "info"
              # Debug
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "2"
              - name: VLLM_CONFIGURE_LOGGING
                value: "1"

              ports:
              - containerPort: 50051
                name: gateway
                protocol: TCP
              - containerPort: 20527
                name: ray
                protocol: TCP
              - containerPort: 24430
                name: ray-client
                protocol: TCP
              - containerPort: 29500  # NCCL coordination port
                name: nccl-coord
                protocol: TCP

              resources:
                limits:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"
                requests:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"

              volumeMounts:
              - name: shmem
                mountPath: /dev/shm

            nodeSelector:
              node.kubernetes.io/instance-type: p5.48xlarge

            tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule

            volumes:
            - name: shmem
              hostPath: 
                path: /dev/shm
                type: Directory

  # JAX Node (Node 1)
  - name: jax-node
    replicas: 1
    template:
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              node-role: jax
          spec:
            serviceAccountName: jax-worker
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet

            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: node-role
                      operator: In
                      values:
                      - vllm
                  topologyKey: kubernetes.io/hostname

            containers:
            - name: jax-container
              image: ghcr.io/nvidia/jax:jax-inference-offloading-2025-12-10
              command:
              - bash
              - -c
              - |
                set -euo pipefail
                apt-get update -y
                apt-get install -y hwloc 
                lstopo
                # Define Variables
                GATEWAY_HOST="${JOBSET_NAME}-gateway-0-0.${JOBSET_NAME}"
                export GATEWAY_URL="${GATEWAY_HOST}:50051"

                HOST_IP=$(hostname -I | awk '{print $1}')
                export JAX_COORDINATOR_ADDRESS="${HOST_IP}:12345"
                export JAX_COORDINATOR_PORT="12345"

                # Wait for gateway
                echo "Waiting for gateway at ${GATEWAY_HOST}:${GATEWAY_PORT}..."
                python3 -c "
                import socket, time, sys
                host = '${GATEWAY_HOST}'
                port = int('${GATEWAY_PORT}')
                timeout = 180
                start = time.time()

                print(f'Checking connectivity to {host}:{port}...')

                while True:
                    try:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(5)
                        result = sock.connect_ex((host, port))
                        sock.close()

                        if result == 0:
                            print(f'Successfully connected to {host}:{port}')
                            sys.exit(0)
                    except Exception as e:
                        pass

                    elapsed = time.time() - start
                    if elapsed > timeout:
                        print(f'Timeout after {timeout}s waiting for {host}:{port}')
                        sys.exit(1)

                    if int(elapsed) % 10 == 0:
                        print(f'Port not ready yet (elapsed: {elapsed:.1f}s), retrying...')
                    time.sleep(2)
                " || exit 1

                echo "Gateway is ready!"
                # Start JAX trainer
                cd /opt/jtbx/jax-inference-offloading/examples
                echo "Starting JAX Trainer..."
                python -u trainer.py 2>&1 | tee trainer-node${JOB_COMPLETION_INDEX}.log

                echo "JAX trainer completed"

              env:
              - name: NCCL_DEBUG
                value: "INFO"

              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']

              # General config
              - name: HF_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: huggingface-token
                    key: token
              - name: MODEL_NAME
                value: "meta-llama/Llama-3.1-8B-Instruct"
              - name: MODEL_PATH
                value: ""

              # JAX distributed config
              - name: JAX_COORDINATOR_PORT
                value: "12345"
              - name: JAX_NUM_PROCESSES
                value: "1"  # Single JAX node for now
              - name: JAX_PROCESS_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              - name: JAX_LOCAL_DEVICE_IDS
                value: "0,1,2,3,4,5,6,7"

              # CUDA settings
              - name: CUDA_DEVICE_ORDER
                value: "PCI_BUS_ID"
              - name: CUDA_DEVICE_MAX_CONNECTIONS
                value: "16"
              - name: CUDA_VISIBLE_DEVICES
                value: "0,1,2,3,4,5,6,7"

              # XLA flags
              - name: XLA_FLAGS
                value: >-
                  --xla_gpu_enable_latency_hiding_scheduler=true
                  --xla_gpu_enable_command_buffer=FUSION,CUBLAS,CUDNN,CUSTOM_CALL
                  --xla_gpu_collective_permute_combine_threshold_bytes=8589934592
                  --xla_gpu_reduce_scatter_combine_threshold_bytes=8589934592
                  --xla_gpu_all_gather_combine_threshold_bytes=8589934592
                  --xla_gpu_all_reduce_combine_threshold_bytes=8589934592

              # Trainer settings
              - name: TRANSFER_MODE
                value: "grouped"
              - name: USE_POLYMORPHIC_MESH
                value: "0"

              # Debug
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "2"
              # EFA
              - name: FI_PROVIDER
                value: "efa"
              # GATEWAY
              - name: GATEWAY_PORT
                value: "50051"
              - name: GATEWAY_URL
                value: "jax-vllm-multinode-gateway-0-0.jax-vllm-multinode:50051"
              # - name: NCCL_SOCKET_IFNAME
              #   value: "enp71s0"

              ports:
              - containerPort: 12345
                name: jax-coord
                protocol: TCP
              - containerPort: 29500  # NCCL coordination port
                name: nccl-coord
                protocol: TCP



              resources:
                limits:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"

                requests:
                  nvidia.com/gpu: "8"
                  vpc.amazonaws.com/efa: "32"

              volumeMounts:
              - name: dshm
                mountPath: /dev/shm

            nodeSelector:
              node.kubernetes.io/instance-type: p5.48xlarge

            tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule

            volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 150Gi

  successPolicy:
    operator: All

  startupPolicy:
    startupPolicyOrder: InOrder

```
This is our hardware 

- Hardware: 2 AWS p5.48xlarge (H100) and 2 m5d.xlarge for the CPU nodes.
- AMI: `Amazon Linux 2023.8.20250915` for P5 and `Amazon Linux 2023.7.20250623` for m5d;

**Comment by anshumang** [comment]
Thanks, this is great for our EKS friends to repro.

Can you also share your cluster arn?

**Comment by Steboss** [comment]
@anshumang  there we go `arn:aws:eks:us-east-1:941377147396:cluster/jax-toolbox-eks`
We updated the cluster yesterday, so we're using a newer AMI, type `AL2023_x86_64_NVIDIA` and release version `1.33.5-20251120`

**Comment by Steboss** [comment]
@erezzarum 
Run a test on a new container, uninstalling the tensorflow libraries aaaand: IT WORKS! NCCL correctly recognize EFA and the tests run with a reasonable timing. 
Thank you so much for your great help!
