### ISSUE TITLE
rdma/fabric.h not found

### ISSUE THREAD

**Issue by tahouse** [aws/aws-ofi-nccl#16]
I've installed EFA driver succesfully on AWS EC2 Deep Learning AMI. I've also built NCCL 2.4.2. When building aws-ofi-nccl, I get the following error during configure

```
[ec2-user@ip-10-0-48-207 aws-ofi-nccl]$ ./configure --with-cuda=/usr/local/cuda/ --with-nccl=$NCCL_HOME --with-mpi=/opt/amazon/efa/bin/
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for size_t... yes
checking for ssize_t... yes
checking for uint64_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for memset... yes
checking for realpath... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking rdma/fabric.h usability... no
checking rdma/fabric.h presence... no
checking for rdma/fabric.h... no
configure: error: unable to find required headers
[ec2-user@ip-10-0-48-207 aws-ofi-nccl]$ make -j 32 NCCL_HOME=$NCCL_HOME
make: *** No targets specified and no makefile found.  Stop.
```

I have libfabric source, but if I make and install it, it overwrites EFA libfabric. Any ideas?

**Comment by rashikakheria** [comment]
@tahouse One of the dependencies of the plugin is libfabric as well which provides the required header. Do you have an installation of that? If yes, please configure plugin to use with `--with-libfabric` parameter.

**Comment by tahouse** [comment]
libfabric is installed by the EFA driver installation script. I'm using Amazon Linux and can confirm that libfabric and libfabric-devel were installed by yum. Is there a specific location I should point to for this installation?

**Comment by rashikakheria** [comment]
Yes, EFA installation script installs the binaries and libraries at `/opt/amazon/efa`. You could use that for configuring the plugin.

**Comment by tahouse** [comment]
`--with-libfabric=/opt/amazon/efa/` solved my problem, thanks.
