### ISSUE TITLE
2 node MPI hang on nccl_message_transfer with EFA 1.5 and Ubuntu 18.04

### ISSUE THREAD

**Issue by amrragab8080** [aws/aws-ofi-nccl#22]
Launch Command:
`/opt/amazon/openmpi/bin/mpirun -np 2 --host 172.0.1.23,172.0.1.161 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH /usr/local/bin/nccl_message_transfer`

Error:
```
INFO: Function: ofi_init Line: 686: NET/OFI Selected Provider is efa
INFO: Function: main Line: 49: NET/OFI Process rank 0 started. NCCLNet device used on ip-172-0-1-23 is AWS Libfabric.
INFO: Function: main Line: 53: NET/OFI Received 1 network devices
INFO: Function: main Line: 57: NET/OFI Server: Listening on dev 0
INFO: Function: ofi_init Line: 686: NET/OFI Selected Provider is efa
INFO: Function: main Line: 49: NET/OFI Process rank 1 started. NCCLNet device used on ip-172-0-1-161 is AWS Libfabric.
INFO: Function: main Line: 53: NET/OFI Received 1 network devices
INFO: Function: main Line: 57: NET/OFI Server: Listening on dev 0
WARN: Function: create_nccl_ofi_component Line: 459: NET/OFI Couldn't open AV. RC: -22, ERROR: Invalid argument
WARN: Function: create_nccl_ofi_component Line: 459: NET/OFI Couldn't open AV. RC: -22, ERROR: Invalid argument
```
MPI hangs, with no other output - looking at top with 100% CPU usage with nccl_message_transger on both nodes.
Additional error in dmesg
```
[ 1632.420956] infiniband efa_0: Failed to process command ALLOC_PD (opcode 14) comp_status 1 err -12
[ 1632.420957] infiniband efa_0: Failed to allocate pd[-12]
[ 1632.726850] infiniband efa_0: Failed to allocate pd[-12]
```

Environment:
Ubuntu 18.04
NVIDIA 430.26 CUDA 10.0
EFA 1.5
```
PATH=/opt/amazon/openmpi/bin:/opt/amazon/efa/bin/:/usr/local/cuda:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/opt/nccl/lib:/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:/usr/local/cuda/lib64:
```
EFA enabled:
```
ubuntu@ip-172-0-1-23:~$ fi_info -p efa
provider: efa
    fabric: EFA-fe80::ca:e4ff:fec9:7534
    domain: efa_0-rdm
    version: 2.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
provider: efa
    fabric: EFA-fe80::ca:e4ff:fec9:7534
    domain: efa_0-dgrm
    version: 2.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_EFA
provider: efa;ofi_rxd
    fabric: EFA-fe80::ca:e4ff:fec9:7534
    domain: efa_0-dgrm
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXD
```

**Comment by amrragab8080** [comment]
I solved the hanging issue. Problem with SG setting. However still seeing:
```
ip-172-0-1-23:2335:2465 [0] NCCL INFO Channel 00 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15
ip-172-0-1-23:2335:2465 [0] NCCL INFO Channel 01 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15
ip-172-0-1-23:2335:2465 [0] NCCL INFO Ring 00 : 15 -> 0 [receive] via NET/AWS Libfabric/0

ip-172-0-1-23:2335:2465 [0] create_nccl_ofi_component:459 NCCL WARN NET/OFI Couldn't open AV. RC: -22, ERROR: Invalid argument
ip-172-0-1-23:2335:2465 [0] NCCL INFO include/net.h:21 -> 2
ip-172-0-1-23:2335:2465 [0] NCCL INFO transport/net.cc:334 -> 2
```
