### ISSUE TITLE
Segfault after/during finalize with OpenMPI

### ISSUE THREAD

**Issue by tmh97** [aws/aws-ofi-nccl#322]
Issue occurs with OpenMPI - 4.1.4, 4.1.5, 5.0.0, 5.0.1 and the latest and greatest aws-ofi-nccl main branch (jan 22 checkout date)

When running any of the `nccl-tests`, or even the basic `nccl_connection` test, I am seeing segfaults after test has completed, likely during MPI_Finalize.

I do not have this issue with using MPICH as the MPI middleware.

I am curious if this is an issue that is known by the EFA team, or alternatively, if any other users have pointed out this issue.

I am hesitant to believe it is an issue with OPX provider since we are fine with MPICH.

Thanks in advance for any help!

**Comment by tmh97** [comment]
TRACE: Function: main Line: 70: NET/OFI Rank 1 uses 1 device for communication
INFO: Function: main Line: 73: NET/OFI Network supports communication using CUDA buffers. Dev: 1
INFO: Function: main Line: 79: NET/OFI Server: Listening on dev 1
TRACE: Function: get_ep Line: 2097: NET/OFI Sendrecv endpoint 0x1cc3630 for dev #1 is created
TRACE: Function: nccl_ofi_init_connection Line: 699: NET/OFI Set endpoint option FI_OPT_CUDA_API_PERMITTED. GDR Supported
INFO: Function: main Line: 91: NET/OFI Send connection request to rank 1
INFO: Function: main Line: 113: NET/OFI Send connection request to rank 0
INFO: Function: main Line: 119: NET/OFI Server: Start accepting requests
TRACE: Function: alloc_and_reg_flush_buff Line: 1119: NET/OFI Registering buffer for flush operations
TRACE: Function: register_mr_buffers Line: 483: NET/OFI Skip registering host buffer. local_mr: 0
INFO: Function: main Line: 123: NET/OFI Successfully accepted connection from rank 0
TRACE: Function: recv_close Line: 907: NET/OFI De-registering buffer for flush operations
INFO: Function: main Line: 97: NET/OFI Server: Start accepting requests
TRACE: Function: alloc_and_reg_flush_buff Line: 1119: NET/OFI Registering buffer for flush operations
TRACE: Function: register_mr_buffers Line: 483: NET/OFI Skip registering host buffer. local_mr: 0
INFO: Function: main Line: 101: NET/OFI Successfully accepted connection from rank 1
TRACE: Function: recv_close Line: 907: NET/OFI De-registering buffer for flush operations
TRACE: Function: nccl_ofi_ep_release_ofi Line: 770: NET/OFI Libfabric endpoint and address vector of dev #1 is released
TRACE: Function: nccl_ofi_ep_release_ofi Line: 770: NET/OFI Libfabric endpoint and address vector of dev #1 is released
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node xxxxxxxx exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by rauteric** [comment]
Hi. I don't recall seeing that error before.

We run these tests regularly with Open MPI and Libfabric's efa and tcp providers. I would suggest checking if you see the same segfault with either of those Libfabric providers.

**Comment by tmh97** [comment]
Closing, this issue was resolved in libfabric by another OPX team member. https://github.com/ofiwg/libfabric/pull/9829
