### ISSUE TITLE
ncclInternalError: Internal check failed. | NET/OFI Unable to insert remote address into address vector for device 1

### ISSUE THREAD

**Issue by emorikawa** [aws/aws-ofi-nccl#663]
# Summary
When running the most basic Torch Distributed all_reduce on two p5.48xlarge nodes, I reliably get the error in the title. Key snippet is:
```
[rank1]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1970, internal error - please report this issue to the NCCL developers, NCCL version 2.20.5
[rank1]: ncclInternalError: Internal check failed.
[rank1]: Last error:
[rank1]: NET/OFI Unable to insert remote address into address vector for device 1. RC: 0
```

# Setup:
- Two identical H100 p5.48xlarge instances.
- Latest [AWS Deep Learning Base GPU AMI (Ubuntu 22.04)](https://aws.amazon.com/releasenotes/aws-deep-learning-base-gpu-ami-ubuntu-22-04/)
- Not containerized
- 32 EFA Network Interfaces attached to them
- Same subnet and AZ. Permissive security group
- Can successfully ping between nodes. Can succssfully connect and run when `NCCL_NET=Socket`

*Relevant software:*
```
Ubuntu 22.04 x86
Linux Kernel: 6.8
NVIDIA Driver:  550.90.07
CUDA: 12.4
Compiled NCCL Version:  2.22.3
EFA Installer: 1.34.0
AWS OFI NCCL: 1.11.0-aws
```

# Execution Command:
```
torchrun \
	--nproc_per_node=1 \
	--nnodes=2 \
	--node_rank=<0 on one side, 1 on the other side> \
	--rdzv_id=123 \
	--rdzv_backend=c10d \
	--rdzv_endpoint=10.0.170.236:1234 \
	nccl_torchrun_test.py
```

# Things I've tried:
- I've tried `all_reduce_perf` from nccl-tests, but reliably get a segfault in `asyncJobLaunch` in all_reduce_perf. Haven't figured that out
- It works fine if `NCCL_NET=Socket`
- Tried setting `FI_PROVIDER=efa`, `NCCL_SOCKET_IFNAME=enp` `NCCL_IB_HCA=rdmap` in all permutations. No effect.

# Contents of `nccl_torchrun_test.py`
```
import torch
import os
import torch.distributed as dist

if __name__ == "__main__":
    dist.init_process_group(
        backend='nccl'
    )
    tensor = torch.ones(1).cuda(int(os.environ['LOCAL_RANK']))
    dist.all_reduce(tensor, op=dist.ReduceOp.SUM)
    print(f"Rank {rank}: {tensor.item()}")
```

# Full Error Output
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/generalistai/dexgpt/nccl_torchrun_test.py", line 23, in <module>
[rank1]:     init_process(rank, size)
[rank1]:   File "/home/ubuntu/generalistai/dexgpt/nccl_torchrun_test.py", line 16, in init_process
[rank1]:     dist.all_reduce(tensor, op=dist.ReduceOp.SUM)
[rank1]:   File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2219, in all_reduce
[rank1]:     work = group.allreduce([tensor], opts)
[rank1]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1970, internal error - please report this issue to the NCCL developers, NCCL version 2.20.5
[rank1]: ncclInternalError: Internal check failed.
[rank1]: Last error:
[rank1]: NET/OFI Unable to insert remote address into address vector for device 1. RC: 0
E1015 23:25:51.980000 129668566423360 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 190657) of binary: /home/ubuntu/miniconda3/envs/dexgpt/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/dexgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
nccl_torchrun_test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-15_23:25:51
  host      : ip-10-0-170-236.us-east-2.compute.internal
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 190657)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by aws-nslick** [comment]
Can you try something like:

```
torchrun \
  --nproc_per_node=gpu # should autodetect to 8 \
  --nnodes=2 # same as what you have \
  --node_rank=<0 on one side, 1 on the other size>
  [...]
```

As-written, AFAIK your command is running is requesting two nodes, but with both thinking they are the `1`th node, and with both running just a single process on that node (producing two rank 1s).

More likely you want one rank per GPU, producing 16 ranks.

**Comment by emorikawa** [comment]
This didn't fix the issue.

I did `--node_rank=0` on the first node and `--node_rank=1` on the second. Also changed `--nproc_per_node=gpu` (or `--nproc_per_node=8`).

Exact same error message: `[rank9]: NET/OFI Unable to insert remote address into address vector for device 1. RC: 0`

**Comment by emorikawa** [comment]
cc maybe @rauteric or @maxtmann. Saw your names on the commit with the "Unable to insert remote address…" error message.

**Comment by aws-nslick** [comment]
Can you check that you have both an inbound and an outbound rule which are explicitly naming your security group? From: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html

> Actions, Edit inbound rules.
> > Choose Add rule.
> > For Type, choose All traffic.
> > For Source type, **choose Custom and paste the security group ID.**

> Actions, Edit outbound rules.
> > Choose Add rule.
> > For Type, choose All traffic.
> > For Destination type, **choose Custom and paste the security group ID.**

You must have both directions, and they should both target the security group directly.

**Comment by emorikawa** [comment]
I've also now tried upgrading to aws-ofi-nccl 1.12.0-aws via the release page.

Now the exact same test hangs for several minutes before throwing the following error. Note that each of the 8 processes has exactly 2 cores each at 100% the entire time while it hangs.

I have no `NCCL_*` nor `IF_*` environment variable set.

```
NCCL_DEBUG=INFO torchrun \
--nproc_per_node=gpu \
--nnodes=2 \
--node_rank=0 \
--rdzv_id=123 \
--rdzv_backend=c10d \
--rdzv_endpoint=10.0.170.236:1234 \
nccl_torchrun_test.py

ip-10-0-170-236:226760:226760 [5] NCCL INFO cudaDriverVersion 12040
ip-10-0-170-236:226760:226760 [5] NCCL INFO Bootstrap : Using enp71s0:10.0.170.236<0>
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Initializing aws-ofi-nccl 1.12.0-aws
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Using Libfabric version 1.22
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Using CUDA driver version 12040
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Configuring AWS-specific options
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Setting provider_filter to efa
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Setting NCCL_NET_FORCE_FLUSH=0 for Hopper GPUs
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Setting NCCL_NVLSTREE_MAX_CHUNKSIZE to 512KiB
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Setting NCCL_NVLS_CHUNKSIZE to 512KiB
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Internode latency set at 75.0 us
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Creating one domain per process
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Using transport protocol RDMA
ip-10-0-170-236:226760:226829 [5] NCCL INFO NET/OFI Selected Provider is efa (found 32 nics)
... same for other ranks on this node ...

... hangs for a few minutes ...

ip-10-0-170-236:226760:226847 [5] process_err_completion:1480 NCCL WARN NET/OFI Operation with NULL context completed with error

ip-10-0-170-236:226760:226847 [5] close_listen_recv_comm:3808 NCCL WARN NET/OFI Unable to free request of listen communicator. Request is still pending. Leaking memory.

ip-10-0-170-236:226760:226847 [5] accept:4011 NCCL WARN NET/OFI Failed to close listen communicator
ip-10-0-170-236:226760:226847 [5] NCCL INFO transport/net.cc:833 -> 2
ip-10-0-170-236:226760:226829 [5] NCCL INFO transport/net.cc:402 -> 2
ip-10-0-170-236:226760:226829 [5] NCCL INFO transport.cc:183 -> 2
ip-10-0-170-236:226760:226829 [5] NCCL INFO init.cc:1222 -> 2
ip-10-0-170-236:226760:226829 [5] NCCL INFO init.cc:1501 -> 2
ip-10-0-170-236:226760:226829 [5] NCCL INFO group.cc:64 -> 2 [Async thread]

ip-10-0-170-236:226760:226847 [5] proxy.cc:1533 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection

ip-10-0-170-236:226760:226847 [5] proxy.cc:1567 NCCL WARN [Proxy Service 13] Failed to execute operation Connect from rank 13, retcode 3
ip-10-0-170-236:226760:226760 [5] NCCL INFO group.cc:418 -> 2
ip-10-0-170-236:226760:226760 [5] NCCL INFO group.cc:95 -> 2

ip-10-0-170-236:226760:226847 [5] nccl_net_ofi_closeRecv:685 NCCL WARN NET/OFI Invalid communicator object provided
ip-10-0-170-236:226760:226847 [5] NCCL INFO transport/net.cc:1015 -> 3
ip-10-0-170-236:226760:226847 [5] NCCL INFO proxy.cc:984 -> 3
ip-10-0-170-236:226760:226847 [5] NCCL INFO proxy.cc:996 -> 3

... then the python stack trace from torch/dstirbuted/run.py comes in for each rank ...
[rank11]: Traceback (most recent call last):
[rank11]:   File "/home/ubuntu/generalistai/dexgpt/nccl_torchrun_test.py", line 11, in <module>
[rank11]:     dist.all_reduce(tensor, op=dist.ReduceOp.SUM)
[rank11]:   File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank11]:     return func(*args, **kwargs)
[rank11]:   File "/home/ubuntu/miniconda3/envs/dexgpt/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2219, in all_reduce
[rank11]:     work = group.allreduce([tensor], opts)
[rank11]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1970, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.20.5
[rank11]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
[rank11]: Last error:
[rank11]: [Proxy Service 11] Failed to execute operation Connect from rank 11, retcode 3
```

**Comment by emorikawa** [comment]
@aws-nslick I had the inbound rule set, but not the outbound rule. This fixed it.

I never think about outbound security group rules! I kept making my inbound rules more and more permissive, but have been decieved the past couple of days because inter-node communication seemed fine for anything socket-based.

Thank you.

**Comment by aws-nslick** [comment]
apologies for the red herring on the torchrun arguments; glad that you were able to figure it out in the end. Let me know if there's any docs you came across as you debugged this that were unclear and we'll try to get them revised.

**Comment by emorikawa** [comment]
Thank you again for your prompt help. The main doc I used was [Get started with EFA and MPI for HPC workloads on Amazon EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html) I think the main thing is stressing the **outbound** security rule requirement. I (and I assume many others) effectively never touch those. I didn't read carefully enough in that step because I assumed my 0.0.0.0 default outbound wildcard applied to EFA. This wasn't even on my radar since inter-node communication worked fine for all socket TCP and ICMP connections.

One other note about that particular doc page is maybe mentioning that anyone who's using your AWS Deep Learning Base images (which I assume are a healthy fraction) don't need to do most of the software install steps.

**Comment by gsong1205** [comment]
Hi, we have run into the same issue but we already have the outbound rules set up for the security group. Besides that also checked OFI version and NCCL version, which seems compatable. aws-ofi-nccl 1.13.1-aws, Libfabric version 1.22, NCCL version 2.23.4.
Besides the `Unable to insert remote address into address vector for device 1` error, we are also seeing `proxy.cc:1147 NCCL WARN ncclProxyCallBlockingUDS call to tpRank 12(30f9f1cce0c9375c) failed : 2` and `proxy.cc:1168 NCCL WARN ncclProxyClientGetFd call to tpRank 12 handle 0x7f487ccd3f40 failed : 2`. Any further guidance on how we can debug this issue? thank you!

**Comment by xman1979** [comment]
I had this issue, but after setting following env, error is gone, not sure which one did the trick

```
export LD_LIBRARY_PATH=/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:/opt/amazon/ofi-nccl/lib:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
export EFA_PATH=/opt/amazon/efa
export OPEN_MPI_PATH=/opt/amazon/openmpi
export NCCL_TUNER_PLUGIN=/opt/amazon/ofi-nccl/lib/x86_64-linux-gnu/libnccl-ofi-tuner.so
export FI_PROVIDER=efa
```
