### ISSUE TITLE
NCCL WARN NET/OFI Disabling shared memory failed: Protocol not available

### ISSUE THREAD

**Issue by ShijunK** [aws/aws-ofi-nccl#803]
Hello, I am trying to use EFA on p4d + docker, built a docker image (EC2) based on https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu 

in the container, when try nccl-tests, got initialization error:

```
/opt/amazon/openmpi/bin/mpirun --allow-run-as-root -np $NUM_GPUS /opt/nccl-tests/build/all_reduce_perf -g 1 -b 8 -e 4GB -f 2 -n 100

...
6f2d8a82d208:1287:1287 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^docker0
6f2d8a82d208:1287:1287 [0] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
6f2d8a82d208:1287:1287 [0] NCCL INFO cudaDriverVersion 12020
6f2d8a82d208:1287:1287 [0] NCCL INFO NCCL version 2.23.4+cuda12.4
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v8 symbol.
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (>= v5). ncclCollNetPlugin symbols v4 and lower are not supported.
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/OFI Initializing aws-ofi-nccl 1.12.1-aws
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/OFI Using Libfabric version 1.22
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/OFI Using CUDA driver version 12020
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/OFI Using transport protocol SENDRECV
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/OFI Selected Provider is tcp (found 1 nics)

6f2d8a82d208:1287:1328 [0] nccl_ofi_ofiutils_init_connection:334 NCCL WARN NET/OFI Disabling shared memory failed: Protocol not available

6f2d8a82d208:1287:1328 [0] nccl_net_ofi_create_plugin:259 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
6f2d8a82d208:1287:1328 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^docker0
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/IB : No device found.
6f2d8a82d208:1287:1328 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^docker0
6f2d8a82d208:1287:1328 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:192.168.0.2<0>
6f2d8a82d208:1287:1328 [0] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
6f2d8a82d208:1287:1328 [0] NCCL INFO Using network Socket
...
```

it looks like the root error is `nccl_ofi_ofiutils_init_connection:334 NCCL WARN NET/OFI Disabling shared memory failed: Protocol not available`. not sure what is the `protocol` here? and how to fix it? 

and, `fi_info -p efa` also throws an error inside docker, but not on the host. 

on guest (inside docker container):
```
 fi_info -p efa
libfabric:1360:1741277340::core:core:cuda_gdrcopy_hmem_init():201<warn> gdr_open failed!
libfabric:1360:1741277340::core:core:cuda_hmem_init():791<warn> gdrcopy initialization failed! gdrcopy will not be used.
libfabric:1360:1741277340::core:core:cuda_gdrcopy_hmem_init():201<warn> gdr_open failed!
libfabric:1360:1741277340::core:core:cuda_hmem_init():791<warn> gdrcopy initialization failed! gdrcopy will not be used.
fi_getinfo: -61 (No data available)
```

on the host:

```
$ fi_info -p efa
provider: efa
    fabric: efa
    domain: rdmap16s27-rdm
    version: 122.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
provider: efa
    fabric: efa
    domain: rdmap16s27-dgrm
    version: 122.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_EFA
```

**Comment by bwbarrett** [comment]
There's a couple of different things I think went wrong.

First, the error message from `fi_info -p efa` in the container indicates that Libfabric could not initialize the GDRCopy device properly.  Given you don't see this outside of the container, I would guess that the GDRCopy kernel module is loaded and that `/dev/gdrdrv` is not being passed into the container.  On P4, you will want GDRCopy available for performance reasons, although it is technically optional.

Second, disabling the shared memory transport failed, I think because TCP doesn't allow it to be disabled and Libfabric had chosen to use TCP instead of EFA.  I'm guessing, again based on the output of `fi_info -p efa`, that this is because the `/dev/infiniband/*` device paths weren't passed into the container either.  Without those, EFA can't be used from a container.

Finally, the fact that the initialization allowed a device other than EFA to be initialized in that run means that the OFI NCCL Plugin wasn't compiled with `--enable-platform-aws`, which is required to make GPUDirect RDMA work properly on P4 platforms.  You'll want to rebuild the plugin to include the `--enable-platform-aws` option.

**Comment by ShijunK** [comment]
thx

unfortunately, I don't have full control of the AMI used and how docker container is launched, will get help to check GDRCopy installation, and adding device mount for infiniband. 

about OFI NCCL Plugin built, I followed two instructions, first from aws's deeplearning container repo: https://github.com/aws/deep-learning-containers/blob/ea48b42ca1745a842d574133edc390f33464c1c7/pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu#L172-L187

second, https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-efa.html, neither of them mentioned about `--enable-platform-aws` flag.   I also tried another way, efa-installer script mentioned at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl.html, it comes with pre-built debs for ubuntu `DEBS/UBUNTU2004/x86_64/libnccl-ofi_1.13.2-1_amd64.deb`. is it built with `--enable-platform-aws` flag?  which way is preferred? using pre-built from efa-installer?  or built from source, with `--enable-platform-aws` flag?

**Comment by bwbarrett** [comment]
Sorry about the documentation; I thought we had found all the places that had instructions for building the NCCL stack and got them up to date, but we clearly missed a few.

The latest EFA installer does include the plugin, and if you can use the latest EFA installer, that's a great starting point.  We only recently (last month) started including the plugin in the installer, which is why instructions are a bit lagging.  Either path works, but it's hard to beat the simplicity of a pre-built binary (and, yes, the installer package is built with the `--enable-platform-aws` flag).

**Comment by Yadan-Wei** [comment]
--enable-platform-aws Doesn't affect the usage of ofi-nccl cause we do the efa test before releasing the container and it works fine. 

1. To start working on EFA, first to make sure your instance is EFA enabled, here is an instruction from EFA to set up EC2 instance with EFA. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/create-efa.html#efa-launch
Cam use ls ```ls /dev/infiniband/uverbs*``` to check EFA devices
 2. When launching container pass efa devices to the container 
```docker run --runtime=nvidia --gpus all -id --name {container_name} --network host --ulimit memlock=-1:-1 --device {efa-devices} {docker_image} bash ```

**Comment by ShijunK** [comment]
thx @Yadan-Wei , @bwbarrett 

I have been able to get a p4d node, with stock AMI from AWS DL AMI, and AWS DL container, passed nccl tests allreduce on both host and guest level, confirmed, OFI NCCL plugin is initialized, libfabric used for NCCL communication. 


So, I was hoping to use AWS DL AMI as reference, and redo steps from https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl.html 

this time, I didn't jump into docker container, but want to confirm EFA and OFI NCCL working on host level first. unfortunately, nccl tests shows OFI NCCL plugin init failed, with different error message from the one I got last time inside docker container. 


nvidia driver and cuda versions:
```
 nvidia-smi -q | head

==============NVSMI LOG==============

Timestamp                                 : Fri Mar 21 17:01:05 2025
Driver Version                            : 535.183.01
CUDA Version                              : 12.2

Attached GPUs                             : 8
GPU 00000000:10:1C.0
    Product Name                          : NVIDIA A100-SXM4-40GB
```

have GDRCopy built and installed, along with NCCL, CUDA and NCCL tests. as well as using EFA installer. 

```
$ fi_info -p efa -t FI_EP_RDM
provider: efa
    fabric: efa
    domain: rdmap16s27-rdm
    version: 122.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
provider: efa
    fabric: efa
    domain: rdmap32s27-rdm
    version: 122.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
provider: efa
    fabric: efa
    domain: rdmap144s27-rdm
    version: 122.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
provider: efa
    fabric: efa
    domain: rdmap160s27-rdm
    version: 122.0
    type: FI_EP_RDM
    protocol: FI_PROTO_EFA
```

gdr drive and infinite band devices:
```
ls /dev/gdrdrv 
/dev/gdrdrv

ls /dev/infiniband/
uverbs0  uverbs1  uverbs2  uverbs3
```

run single gpu test:
```
NCCL_DEBUG=INFO $HOME/nccl-tests/build/all_reduce_perf -b 8 -e 1G -f 2 -g 1 -c 1 -n 100

...
 [0] NCCL INFO NET/OFI Initializing aws-ofi-nccl 1.13.2-aws
 [0] NCCL INFO NET/OFI Using Libfabric version 1.22
 [0] NCCL INFO NET/OFI Using CUDA driver version 12020 with runtime 12020
 [0] NCCL INFO NET/OFI Configuring AWS-specific options
 [0] NCCL INFO NET/OFI Setting provider_filter to efa
 [0] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
 [0] NCCL INFO NET/OFI Setting NCCL_NVLSTREE_MAX_CHUNKSIZE to 512KiB
 [0] NCCL INFO NET/OFI Setting NCCL_NVLS_CHUNKSIZE to 512KiB
 [0] NCCL INFO NET/OFI Running on p4d.24xlarge platform, Setting NCCL_TOPO_FILE environment variable to /opt/amazon/ofi-nccl/share/aws-ofi-nccl/xml/p4d-24xl-topo.xml
 [0] NCCL INFO NET/OFI Internode latency set at 75.0 us
 [0] NCCL INFO NET/OFI Using transport protocol SENDRECV (platform set)
 [0] NCCL INFO NET/OFI Selected Provider is efa (found 4 nics)
 [0] NCCL INFO NET/OFI Creating one domain per process
 [0] NCCL INFO NET/OFI Could not disable CUDA API usage for HMEM, disabling GDR

 [0] platform_config_endpoint:589 NCCL WARN NET/OFI GDR disabled on GDR-supported instance type p4d.24xlarge

 [0] nccl_net_ofi_device_get_ep:740 NCCL WARN NET/OFI Creating new endpoint for device efa failed: Invalid argument

 [0] nccl_net_ofi_create_plugin:341 NCCL WARN NET/OFI aws-ofi-nccl initialization failed

 [0] nccl_net_ofi_init:134 NCCL WARN NET/OFI Initializing plugin failed
 [0] NCCL INFO NET/IB : No device found.
...
```


I could see two messages stand out:
- `Could not disable CUDA API usage for HMEM, disabling GDR`
- `Creating new endpoint for device efa failed: Invalid argument`

any ideas what could be the root cause for these two issues?

**Comment by ShijunK** [comment]
a bit further info, the efa installer was done by another team ahead of time on custom AMI. I tried to uninstall, and re-install. and got error during `Testing EFA device`. 

```
== Testing EFA device ==
Localhost fi_pingpong test: Attempt 1 (max 3)...
Starting server on port 55679...
Starting client on port 62457...
Server Log:
libfabric:633363:1742579443::efa:domain:efa_domain_hmem_info_init_cuda():170<warn> Failed to register CUDA buffer with the EFA device, FI_HMEM transfers that require peer to peer support will fail.
Client Log:
libfabric:633465:1742579443::efa:domain:efa_domain_hmem_info_init_cuda():170<warn> Failed to register CUDA buffer with the EFA device, FI_HMEM transfers that require peer to peer support will fail.
Error: fi_pingpong test failed because of timeout.
===================================================

```

**Comment by bwbarrett** [comment]
What does `cat /sys/class/infiniband/rdmap*/device/p2p` return?  Given the last error message, I think the problem is that you have a combination of Nvidia driver, kernel version, and EFA version that do not support peer to peer memory registration.  The general cause for that is using the proprietary Nvidia driver with a recent kernel (recently patched, as some changes that broke the proprietary driver and peer to peer transactions were backported by the distros).  In addition to the output of the command above, knowing the distro, kernel version, and Nvidia driver type / version would be helpful.

**Comment by bwbarrett** [comment]
Yeah, pretty sure this is a peer to peer incompatibility problem.  If you look at the `nvidia-kernel-source` package list, you should see something like `nvidia-kernel-source-535-open`.  If the `-open` isn't listed, you're using the proprietary drivers and need to switch to the open stack.

**Comment by ShijunK** [comment]
```
$ dpkg -l nvidia* | grep ii
ii  nvidia-compute-utils-535      535.183.01-0ubuntu1 amd64        NVIDIA compute utilities
ii  nvidia-dkms-535               535.183.01-0ubuntu1 amd64        NVIDIA DKMS package
ii  nvidia-driver-535             535.183.01-0ubuntu1 amd64        NVIDIA driver metapackage
ii  nvidia-kernel-common-535      535.183.01-0ubuntu1 amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-535      535.183.01-0ubuntu1 amd64        NVIDIA kernel source package
ii  nvidia-modprobe               535.183.01-0ubuntu1 amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-prime                  0.8.17.1            all          Tools to enable NVIDIA's Prime
ii  nvidia-settings               535.183.01-0ubuntu1 amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-535              535.183.01-0ubuntu1 amd64        NVIDIA driver support binaries

```

do you refer to this package `nvidia-kernel-source-535`?  where can I find more information about `the open stack.`?

**Comment by bwbarrett** [comment]
https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/index.html#kernel-modules
